package com.dxc.darklightrest.entity;
// Generated 2018-5-21 13:58:10 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BaseStocks generated by hbm2java
 */
@Entity
@Table(name = "base_stocks", catalog = "darklight")
public class BaseStocks implements java.io.Serializable {

	private Integer id;
	private int industryCd;
	private String stockCode;
	private String stockName;
	private String shortName;
	private String keyWords;
	private String totalStock;
	private String stockWin;
	private String passStock;
	private Date createDtm;
	private Date updDtm;

	public BaseStocks() {
	}

	public BaseStocks(int industryCd, Date createDtm, Date updDtm) {
		this.industryCd = industryCd;
		this.createDtm = createDtm;
		this.updDtm = updDtm;
	}

	public BaseStocks(int industryCd, String stockCode, String stockName, String shortName, String keyWords,
			String totalStock, String stockWin, String passStock, Date createDtm, Date updDtm) {
		this.industryCd = industryCd;
		this.stockCode = stockCode;
		this.stockName = stockName;
		this.shortName = shortName;
		this.keyWords = keyWords;
		this.totalStock = totalStock;
		this.stockWin = stockWin;
		this.passStock = passStock;
		this.createDtm = createDtm;
		this.updDtm = updDtm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "industry_cd", nullable = false)
	public int getIndustryCd() {
		return this.industryCd;
	}

	public void setIndustryCd(int industryCd) {
		this.industryCd = industryCd;
	}

	@Column(name = "stock_code", length = 10)
	public String getStockCode() {
		return this.stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	@Column(name = "stock_name", length = 256)
	public String getStockName() {
		return this.stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	@Column(name = "short_name", length = 20)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "key_words", length = 100)
	public String getKeyWords() {
		return this.keyWords;
	}

	public void setKeyWords(String keyWords) {
		this.keyWords = keyWords;
	}

	@Column(name = "total_stock", length = 10)
	public String getTotalStock() {
		return this.totalStock;
	}

	public void setTotalStock(String totalStock) {
		this.totalStock = totalStock;
	}

	@Column(name = "stock_win", length = 10)
	public String getStockWin() {
		return this.stockWin;
	}

	public void setStockWin(String stockWin) {
		this.stockWin = stockWin;
	}

	@Column(name = "pass_stock", length = 10)
	public String getPassStock() {
		return this.passStock;
	}

	public void setPassStock(String passStock) {
		this.passStock = passStock;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dtm", nullable = false, length = 19)
	public Date getCreateDtm() {
		return this.createDtm;
	}

	public void setCreateDtm(Date createDtm) {
		this.createDtm = createDtm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_dtm", nullable = false, length = 19)
	public Date getUpdDtm() {
		return this.updDtm;
	}

	public void setUpdDtm(Date updDtm) {
		this.updDtm = updDtm;
	}

}
