package com.dxc.darklightrest.entity;
// Generated 2018-5-21 13:58:10 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BlackStocks generated by hbm2java
 */
@Entity
@Table(name = "black_stocks", catalog = "darklight")
public class BlackStocks implements java.io.Serializable {

	private String id;
	private String stockCode;
	private Date startDate;
	private Date endDate;
	private int removed;
	private Double yieldRate;
	private Date createDt;
	private Date updateDt;
	private String priceWave;

	public BlackStocks() {
	}

	public BlackStocks(String id, String stockCode, Date startDate, int removed, Date createDt, Date updateDt) {
		this.id = id;
		this.stockCode = stockCode;
		this.startDate = startDate;
		this.removed = removed;
		this.createDt = createDt;
		this.updateDt = updateDt;
	}

	public BlackStocks(String id, String stockCode, Date startDate, Date endDate, int removed, Double yieldRate,
			Date createDt, Date updateDt, String priceWave) {
		this.id = id;
		this.stockCode = stockCode;
		this.startDate = startDate;
		this.endDate = endDate;
		this.removed = removed;
		this.yieldRate = yieldRate;
		this.createDt = createDt;
		this.updateDt = updateDt;
		this.priceWave = priceWave;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "stock_code", nullable = false, length = 6)
	public String getStockCode() {
		return this.stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "removed", nullable = false)
	public int getRemoved() {
		return this.removed;
	}

	public void setRemoved(int removed) {
		this.removed = removed;
	}

	@Column(name = "yield_rate", precision = 22, scale = 0)
	public Double getYieldRate() {
		return this.yieldRate;
	}

	public void setYieldRate(Double yieldRate) {
		this.yieldRate = yieldRate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 19)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 19)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "price_wave", length = 20)
	public String getPriceWave() {
		return this.priceWave;
	}

	public void setPriceWave(String priceWave) {
		this.priceWave = priceWave;
	}

}
