package com.dxc.darklightrest.entity;
// Generated 2018-5-21 13:58:10 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IndividualStockNews generated by hbm2java
 */
@Entity
@Table(name = "individual_stock_news", catalog = "darklight")
public class IndividualStockNews implements java.io.Serializable {

	private String id;
	private String stockCode;
	private String title;
	private String newsLink;
	private Date pubDate;
	private Date fetchDate;

	public IndividualStockNews() {
	}

	public IndividualStockNews(String id) {
		this.id = id;
	}

	public IndividualStockNews(String id, String stockCode, String title, String newsLink, Date pubDate,
			Date fetchDate) {
		this.id = id;
		this.stockCode = stockCode;
		this.title = title;
		this.newsLink = newsLink;
		this.pubDate = pubDate;
		this.fetchDate = fetchDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "stock_code", length = 20)
	public String getStockCode() {
		return this.stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	@Column(name = "title", length = 256)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "news_link", length = 256)
	public String getNewsLink() {
		return this.newsLink;
	}

	public void setNewsLink(String newsLink) {
		this.newsLink = newsLink;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pub_date", length = 19)
	public Date getPubDate() {
		return this.pubDate;
	}

	public void setPubDate(Date pubDate) {
		this.pubDate = pubDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fetch_date", length = 19)
	public Date getFetchDate() {
		return this.fetchDate;
	}

	public void setFetchDate(Date fetchDate) {
		this.fetchDate = fetchDate;
	}

}
