package com.dxc.darklightrest.entity;
// Generated 2018-5-21 13:58:10 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Industry generated by hbm2java
 */
@Entity
@Table(name = "industry", catalog = "darklight")
public class Industry implements java.io.Serializable {

	private Integer industryCd;
	private String industryNm;
	private Date createDtm;
	private Date updDtm;

	public Industry() {
	}

	public Industry(Date createDtm, Date updDtm) {
		this.createDtm = createDtm;
		this.updDtm = updDtm;
	}

	public Industry(String industryNm, Date createDtm, Date updDtm) {
		this.industryNm = industryNm;
		this.createDtm = createDtm;
		this.updDtm = updDtm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "industry_cd", unique = true, nullable = false)
	public Integer getIndustryCd() {
		return this.industryCd;
	}

	public void setIndustryCd(Integer industryCd) {
		this.industryCd = industryCd;
	}

	@Column(name = "industry_nm", length = 256)
	public String getIndustryNm() {
		return this.industryNm;
	}

	public void setIndustryNm(String industryNm) {
		this.industryNm = industryNm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dtm", nullable = false, length = 19)
	public Date getCreateDtm() {
		return this.createDtm;
	}

	public void setCreateDtm(Date createDtm) {
		this.createDtm = createDtm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_dtm", nullable = false, length = 19)
	public Date getUpdDtm() {
		return this.updDtm;
	}

	public void setUpdDtm(Date updDtm) {
		this.updDtm = updDtm;
	}

}
