package com.dxc.darklightrest.entity;
// Generated 2018-6-13 11:18:16 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KpiMorningStar generated by hbm2java
 */
@Entity
@Table(name = "kpi_morning_star", catalog = "darklight")
public class KpiMorningStar implements java.io.Serializable {

	private Integer id;
	private String stockCode;
	private String stageDateStr;
	private String stageComments;
	private float dayCutOffYield;
	private String stageEndDatestr;
	private float weight;

	public KpiMorningStar() {
	}

	public KpiMorningStar(String stockCode, String stageDateStr, float dayCutOffYield, float weight) {
		this.stockCode = stockCode;
		this.stageDateStr = stageDateStr;
		this.dayCutOffYield = dayCutOffYield;
		this.weight = weight;
	}

	public KpiMorningStar(String stockCode, String stageDateStr, String stageComments, float dayCutOffYield,
			String stageEndDatestr, float weight) {
		this.stockCode = stockCode;
		this.stageDateStr = stageDateStr;
		this.stageComments = stageComments;
		this.dayCutOffYield = dayCutOffYield;
		this.stageEndDatestr = stageEndDatestr;
		this.weight = weight;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "stock_code", nullable = false, length = 6)
	public String getStockCode() {
		return this.stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	@Column(name = "stage_date_str", nullable = false, length = 10)
	public String getStageDateStr() {
		return this.stageDateStr;
	}

	public void setStageDateStr(String stageDateStr) {
		this.stageDateStr = stageDateStr;
	}

	@Column(name = "stage_comments", length = 512)
	public String getStageComments() {
		return this.stageComments;
	}

	public void setStageComments(String stageComments) {
		this.stageComments = stageComments;
	}

	@Column(name = "day_cut_off_yield", nullable = false, precision = 10)
	public float getDayCutOffYield() {
		return this.dayCutOffYield;
	}

	public void setDayCutOffYield(float dayCutOffYield) {
		this.dayCutOffYield = dayCutOffYield;
	}

	@Column(name = "stage_end_datestr", length = 10)
	public String getStageEndDatestr() {
		return this.stageEndDatestr;
	}

	public void setStageEndDatestr(String stageEndDatestr) {
		this.stageEndDatestr = stageEndDatestr;
	}

	@Column(name = "weight", nullable = false, precision = 10)
	public float getWeight() {
		return this.weight;
	}

	public void setWeight(float weight) {
		this.weight = weight;
	}

}
