package com.dxc.darklightrest.entity;
// Generated 2018-5-21 13:58:10 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockComments generated by hbm2java
 */
@Entity
@Table(name = "stock_comments", catalog = "darklight")
public class StockComments implements java.io.Serializable {

	private String id;
	private String author;
	private String title;
	private String newsLink;
	private String correct;
	private String keyComments;
	private Date pubDate;
	private Date fetchDate;

	public StockComments() {
	}

	public StockComments(String id) {
		this.id = id;
	}

	public StockComments(String id, String author, String title, String newsLink, String correct, String keyComments,
			Date pubDate, Date fetchDate) {
		this.id = id;
		this.author = author;
		this.title = title;
		this.newsLink = newsLink;
		this.correct = correct;
		this.keyComments = keyComments;
		this.pubDate = pubDate;
		this.fetchDate = fetchDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "author", length = 20)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "title", length = 256)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "news_link", length = 256)
	public String getNewsLink() {
		return this.newsLink;
	}

	public void setNewsLink(String newsLink) {
		this.newsLink = newsLink;
	}

	@Column(name = "correct", length = 16)
	public String getCorrect() {
		return this.correct;
	}

	public void setCorrect(String correct) {
		this.correct = correct;
	}

	@Column(name = "key_comments", length = 256)
	public String getKeyComments() {
		return this.keyComments;
	}

	public void setKeyComments(String keyComments) {
		this.keyComments = keyComments;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pub_date", length = 19)
	public Date getPubDate() {
		return this.pubDate;
	}

	public void setPubDate(Date pubDate) {
		this.pubDate = pubDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fetch_date", length = 19)
	public Date getFetchDate() {
		return this.fetchDate;
	}

	public void setFetchDate(Date fetchDate) {
		this.fetchDate = fetchDate;
	}

}
