package com.dxc.darklightrest.entity;
// Generated 2018-5-21 13:58:10 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockModelMount generated by hbm2java
 */
@Entity
@Table(name = "stock_model_mount", catalog = "darklight")
public class StockModelMount implements java.io.Serializable {

	private StockModelMountId id;
	private Double avgMount;
	private int flagPhase;
	private Double avgWeight;
	private Date createDtm;
	private Double avgPrice;
	private Date endDate;

	public StockModelMount() {
	}

	public StockModelMount(StockModelMountId id, int flagPhase) {
		this.id = id;
		this.flagPhase = flagPhase;
	}

	public StockModelMount(StockModelMountId id, Double avgMount, int flagPhase, Double avgWeight, Date createDtm,
			Double avgPrice, Date endDate) {
		this.id = id;
		this.avgMount = avgMount;
		this.flagPhase = flagPhase;
		this.avgWeight = avgWeight;
		this.createDtm = createDtm;
		this.avgPrice = avgPrice;
		this.endDate = endDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "stockCode", column = @Column(name = "stock_code", nullable = false, length = 10)),
			@AttributeOverride(name = "stockDate", column = @Column(name = "stock_date", nullable = false, length = 10)) })
	public StockModelMountId getId() {
		return this.id;
	}

	public void setId(StockModelMountId id) {
		this.id = id;
	}

	@Column(name = "avg_mount", precision = 20, scale = 4)
	public Double getAvgMount() {
		return this.avgMount;
	}

	public void setAvgMount(Double avgMount) {
		this.avgMount = avgMount;
	}

	@Column(name = "flag_phase", nullable = false)
	public int getFlagPhase() {
		return this.flagPhase;
	}

	public void setFlagPhase(int flagPhase) {
		this.flagPhase = flagPhase;
	}

	@Column(name = "avg_weight", precision = 20, scale = 4)
	public Double getAvgWeight() {
		return this.avgWeight;
	}

	public void setAvgWeight(Double avgWeight) {
		this.avgWeight = avgWeight;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dtm", length = 19)
	public Date getCreateDtm() {
		return this.createDtm;
	}

	public void setCreateDtm(Date createDtm) {
		this.createDtm = createDtm;
	}

	@Column(name = "avg_price", precision = 20, scale = 4)
	public Double getAvgPrice() {
		return this.avgPrice;
	}

	public void setAvgPrice(Double avgPrice) {
		this.avgPrice = avgPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
