package com.dxc.darklightrest.entity;
// Generated 2018-5-21 13:58:10 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StockModelMountId generated by hbm2java
 */
@Embeddable
public class StockModelMountId implements java.io.Serializable {

	private String stockCode;
	private String stockDate;

	public StockModelMountId() {
	}

	public StockModelMountId(String stockCode, String stockDate) {
		this.stockCode = stockCode;
		this.stockDate = stockDate;
	}

	@Column(name = "stock_code", nullable = false, length = 10)
	public String getStockCode() {
		return this.stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	@Column(name = "stock_date", nullable = false, length = 10)
	public String getStockDate() {
		return this.stockDate;
	}

	public void setStockDate(String stockDate) {
		this.stockDate = stockDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StockModelMountId))
			return false;
		StockModelMountId castOther = (StockModelMountId) other;

		return ((this.getStockCode() == castOther.getStockCode()) || (this.getStockCode() != null
				&& castOther.getStockCode() != null && this.getStockCode().equals(castOther.getStockCode())))
				&& ((this.getStockDate() == castOther.getStockDate()) || (this.getStockDate() != null
						&& castOther.getStockDate() != null && this.getStockDate().equals(castOther.getStockDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStockCode() == null ? 0 : this.getStockCode().hashCode());
		result = 37 * result + (getStockDate() == null ? 0 : this.getStockDate().hashCode());
		return result;
	}

}
