package com.dxc.darklightrest.entity;
// Generated 2018-5-21 13:58:10 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockCurrentPrice generated by hbm2java
 */
@Entity
@Table(name = "stock_current_price", catalog = "darklight")
public class StockCurrentPrice implements java.io.Serializable {

	private Integer id;
	private String stockCode;
	private String userId;
	private String stockName;
	private Double stockPrice;
	private Double stockUpdownPrice;
	private Double stockUpdownPercent;
	private Integer stockDealMount;
	private Date createDtm;

	public StockCurrentPrice() {
	}

	public StockCurrentPrice(String stockCode, String userId, String stockName) {
		this.stockCode = stockCode;
		this.userId = userId;
		this.stockName = stockName;
	}

	public StockCurrentPrice(String stockCode, String userId, String stockName, Double stockPrice,
			Double stockUpdownPrice, Double stockUpdownPercent, Integer stockDealMount, Date createDtm) {
		this.stockCode = stockCode;
		this.userId = userId;
		this.stockName = stockName;
		this.stockPrice = stockPrice;
		this.stockUpdownPrice = stockUpdownPrice;
		this.stockUpdownPercent = stockUpdownPercent;
		this.stockDealMount = stockDealMount;
		this.createDtm = createDtm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "stock_code", nullable = false, length = 11)
	public String getStockCode() {
		return this.stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	@Column(name = "user_id", nullable = false, length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "stock_name", nullable = false, length = 30)
	public String getStockName() {
		return this.stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	@Column(name = "stock_price", precision = 10, scale = 4)
	public Double getStockPrice() {
		return this.stockPrice;
	}

	public void setStockPrice(Double stockPrice) {
		this.stockPrice = stockPrice;
	}

	@Column(name = "stock_updown_price", precision = 10, scale = 4)
	public Double getStockUpdownPrice() {
		return this.stockUpdownPrice;
	}

	public void setStockUpdownPrice(Double stockUpdownPrice) {
		this.stockUpdownPrice = stockUpdownPrice;
	}

	@Column(name = "stock_updown_percent", precision = 10, scale = 4)
	public Double getStockUpdownPercent() {
		return this.stockUpdownPercent;
	}

	public void setStockUpdownPercent(Double stockUpdownPercent) {
		this.stockUpdownPercent = stockUpdownPercent;
	}

	@Column(name = "stock_deal_mount")
	public Integer getStockDealMount() {
		return this.stockDealMount;
	}

	public void setStockDealMount(Integer stockDealMount) {
		this.stockDealMount = stockDealMount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dtm", length = 19)
	public Date getCreateDtm() {
		return this.createDtm;
	}

	public void setCreateDtm(Date createDtm) {
		this.createDtm = createDtm;
	}

}
